# Auto-generated by entrypoint.sh from nginx.conf.tpl — do not edit directly
error_log /var/log/nginx/error.log;

events {
    worker_connections 1024;
}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    # ---- OpenClaw (HTTPS) — mapped to host port NGINX_OPENCLAW_PORT ----
    server {
        listen 443 ssl;
        server_name ${TAILSCALE_HOSTNAME};

        ssl_certificate     /etc/ssl/openclaw/cert.pem;
        ssl_certificate_key /etc/ssl/openclaw/key.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;

        location / {
            proxy_pass         http://openclaw-gateway:18789;
            proxy_http_version 1.1;

            proxy_set_header   Upgrade    $http_upgrade;
            proxy_set_header   Connection $connection_upgrade;

            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }

    # ---- Ollama API (SSL) — port ${NGINX_OLLAMA_PORT} ----
    server {
        listen ${NGINX_OLLAMA_PORT} ssl;
        server_name ${TAILSCALE_HOSTNAME};

        ssl_certificate     /etc/ssl/openclaw/cert.pem;
        ssl_certificate_key /etc/ssl/openclaw/key.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            proxy_pass         http://ollama:11434;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
            proxy_buffering    off;
        }
    }

    # ---- n8n (HTTPS) — port ${NGINX_N8N_PORT} ----
    server {
        listen ${NGINX_N8N_PORT} ssl;
        server_name ${TAILSCALE_HOSTNAME};

        ssl_certificate     /etc/ssl/openclaw/cert.pem;
        ssl_certificate_key /etc/ssl/openclaw/key.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;

        location / {
            proxy_pass         http://n8n:5678;
            proxy_http_version 1.1;

            proxy_set_header   Upgrade    $http_upgrade;
            proxy_set_header   Connection $connection_upgrade;

            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }

    # ---- HTTP — rejected (SSL-only enforcement) ----
    server {
        listen 80 default_server;
        return 444;
    }
}
